
export const PERMISSIONS = {
    // === USUÁRIOS (11) ===
    MANAGE_USERS: 'MANAGE_USERS',
    CREATE_CAMBISTA: 'CREATE_CAMBISTA',
    EDIT_CAMBISTA: 'EDIT_CAMBISTA',
    DELETE_CAMBISTA: 'DELETE_CAMBISTA',
    CREATE_COBRADOR: 'CREATE_COBRADOR',
    EDIT_COBRADOR: 'EDIT_COBRADOR',
    DELETE_COBRADOR: 'DELETE_COBRADOR',
    CREATE_ADMIN: 'CREATE_ADMIN',
    EDIT_ADMIN: 'EDIT_ADMIN',
    DELETE_ADMIN: 'DELETE_ADMIN',
    EDIT_USER_LIMITS: 'EDIT_USER_LIMITS',

    // === JOGOS (4) ===
    VIEW_GAMES: 'VIEW_GAMES',
    CREATE_GAME: 'CREATE_GAME',
    EDIT_GAME: 'EDIT_GAME',
    DELETE_GAME: 'DELETE_GAME',

    // === SORTEIOS (4) ===
    VIEW_DRAWS: 'VIEW_DRAWS',
    CREATE_DRAW: 'CREATE_DRAW',
    EDIT_DRAW: 'EDIT_DRAW',
    DELETE_DRAW: 'DELETE_DRAW',

    // === ÁREAS (4) ===
    VIEW_AREAS: 'VIEW_AREAS',
    CREATE_AREA: 'CREATE_AREA',
    EDIT_AREA: 'EDIT_AREA',
    DELETE_AREA: 'DELETE_AREA',

    // === RELATÓRIOS (5) ===
    VIEW_SALES_REPORT: 'VIEW_SALES_REPORT',
    VIEW_FINANCIAL_REPORT: 'VIEW_FINANCIAL_REPORT',
    VIEW_ANALYTICS: 'VIEW_ANALYTICS',
    EXPORT_REPORTS: 'EXPORT_REPORTS',
    VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

    // === FINANCEIRO (5) ===
    VIEW_FINANCIALS: 'VIEW_FINANCIALS',
    MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
    VIEW_COMMISSIONS: 'VIEW_COMMISSIONS',
    EDIT_COMMISSIONS: 'EDIT_COMMISSIONS',
    MANAGE_DAILY_CLOSE: 'MANAGE_DAILY_CLOSE',

    // === BILHETES (4) ===
    VIEW_TICKETS: 'VIEW_TICKETS',
    CANCEL_TICKET: 'CANCEL_TICKET',
    VALIDATE_TICKET: 'VALIDATE_TICKET',
    EDIT_TICKET: 'EDIT_TICKET',

    // === PALPITA AI (3) ===
    VIEW_PALPITA: 'VIEW_PALPITA',
    CREATE_PALPITA_DRAW: 'CREATE_PALPITA_DRAW',
    MANAGE_PALPITA_RESULTS: 'MANAGE_PALPITA_RESULTS',

    // === SISTEMA (5) ===
    MANAGE_SETTINGS: 'MANAGE_SETTINGS',
    MANAGE_COMPANY: 'MANAGE_COMPANY',
    MANAGE_DEVICES: 'MANAGE_DEVICES',
    VIEW_LOGS: 'VIEW_LOGS',
    MANAGE_ANNOUNCEMENTS: 'MANAGE_ANNOUNCEMENTS',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

export const PERMISSION_LABELS: Record<string, string> = {
    // Usuários
    [PERMISSIONS.MANAGE_USERS]: 'Visualizar Lista de Usuários',
    [PERMISSIONS.CREATE_CAMBISTA]: 'Criar Cambistas',
    [PERMISSIONS.EDIT_CAMBISTA]: 'Editar Cambistas',
    [PERMISSIONS.DELETE_CAMBISTA]: 'Excluir Cambistas',
    [PERMISSIONS.CREATE_COBRADOR]: 'Criar Cobradores',
    [PERMISSIONS.EDIT_COBRADOR]: 'Editar Cobradores',
    [PERMISSIONS.DELETE_COBRADOR]: 'Excluir Cobradores',
    [PERMISSIONS.CREATE_ADMIN]: 'Criar Administradores',
    [PERMISSIONS.EDIT_ADMIN]: 'Editar Administradores',
    [PERMISSIONS.DELETE_ADMIN]: 'Excluir Administradores',
    [PERMISSIONS.EDIT_USER_LIMITS]: 'Editar Limites de Usuários',

    // Jogos
    [PERMISSIONS.VIEW_GAMES]: 'Visualizar Jogos',
    [PERMISSIONS.CREATE_GAME]: 'Criar Jogos',
    [PERMISSIONS.EDIT_GAME]: 'Editar Jogos',
    [PERMISSIONS.DELETE_GAME]: 'Excluir Jogos',

    // Sorteios
    [PERMISSIONS.VIEW_DRAWS]: 'Visualizar Sorteios',
    [PERMISSIONS.CREATE_DRAW]: 'Criar Sorteios',
    [PERMISSIONS.EDIT_DRAW]: 'Editar Sorteios',
    [PERMISSIONS.DELETE_DRAW]: 'Excluir Sorteios',

    // Áreas
    [PERMISSIONS.VIEW_AREAS]: 'Visualizar Áreas/Praças',
    [PERMISSIONS.CREATE_AREA]: 'Criar Áreas/Praças',
    [PERMISSIONS.EDIT_AREA]: 'Editar Áreas/Praças',
    [PERMISSIONS.DELETE_AREA]: 'Excluir Áreas/Praças',

    // Relatórios
    [PERMISSIONS.VIEW_SALES_REPORT]: 'Ver Relatório de Vendas',
    [PERMISSIONS.VIEW_FINANCIAL_REPORT]: 'Ver Relatório Financeiro',
    [PERMISSIONS.VIEW_ANALYTICS]: 'Ver Analytics e Dashboard',
    [PERMISSIONS.EXPORT_REPORTS]: 'Exportar Relatórios',
    [PERMISSIONS.VIEW_AUDIT_LOGS]: 'Ver Logs de Auditoria',

    // Financeiro
    [PERMISSIONS.VIEW_FINANCIALS]: 'Acessar Menu Financeiro',
    [PERMISSIONS.MANAGE_PAYMENTS]: 'Gerenciar Pagamentos',
    [PERMISSIONS.VIEW_COMMISSIONS]: 'Visualizar Comissões',
    [PERMISSIONS.EDIT_COMMISSIONS]: 'Editar Comissões',
    [PERMISSIONS.MANAGE_DAILY_CLOSE]: 'Gerenciar Fechamento de Caixa',

    // Bilhetes
    [PERMISSIONS.VIEW_TICKETS]: 'Visualizar Bilhetes',
    [PERMISSIONS.CANCEL_TICKET]: 'Cancelar Bilhetes',
    [PERMISSIONS.VALIDATE_TICKET]: 'Validar Bilhetes',
    [PERMISSIONS.EDIT_TICKET]: 'Editar Bilhetes',

    // Sistema
    [PERMISSIONS.MANAGE_SETTINGS]: 'Gerenciar Configurações',
    [PERMISSIONS.MANAGE_COMPANY]: 'Gerenciar Empresa',
    [PERMISSIONS.MANAGE_DEVICES]: 'Gerenciar Dispositivos POS',
    [PERMISSIONS.VIEW_LOGS]: 'Visualizar Logs do Sistema',
    [PERMISSIONS.MANAGE_ANNOUNCEMENTS]: 'Gerenciar Avisos',

    // Palpita Ai
    [PERMISSIONS.VIEW_PALPITA]: 'Visualizar Concursos Palpita Ai',
    [PERMISSIONS.CREATE_PALPITA_DRAW]: 'Criar Concursos Palpita Ai',
    [PERMISSIONS.MANAGE_PALPITA_RESULTS]: 'Apurar Resultados Palpita Ai',
};

export const PERMISSION_GROUPS = {
    'Usuários': [
        PERMISSIONS.MANAGE_USERS,
        PERMISSIONS.CREATE_CAMBISTA,
        PERMISSIONS.EDIT_CAMBISTA,
        PERMISSIONS.DELETE_CAMBISTA,
        PERMISSIONS.CREATE_COBRADOR,
        PERMISSIONS.EDIT_COBRADOR,
        PERMISSIONS.DELETE_COBRADOR,
        PERMISSIONS.CREATE_ADMIN,
        PERMISSIONS.EDIT_ADMIN,
        PERMISSIONS.DELETE_ADMIN,
        PERMISSIONS.EDIT_USER_LIMITS,
    ],
    'Jogos': [
        PERMISSIONS.VIEW_GAMES,
        PERMISSIONS.CREATE_GAME,
        PERMISSIONS.EDIT_GAME,
        PERMISSIONS.DELETE_GAME,
    ],
    'Sorteios': [
        PERMISSIONS.VIEW_DRAWS,
        PERMISSIONS.CREATE_DRAW,
        PERMISSIONS.EDIT_DRAW,
        PERMISSIONS.DELETE_DRAW,
    ],
    'Áreas/Praças': [
        PERMISSIONS.VIEW_AREAS,
        PERMISSIONS.CREATE_AREA,
        PERMISSIONS.EDIT_AREA,
        PERMISSIONS.DELETE_AREA,
    ],
    'Relatórios': [
        PERMISSIONS.VIEW_SALES_REPORT,
        PERMISSIONS.VIEW_FINANCIAL_REPORT,
        PERMISSIONS.VIEW_ANALYTICS,
        PERMISSIONS.EXPORT_REPORTS,
        PERMISSIONS.VIEW_AUDIT_LOGS,
    ],
    'Financeiro': [
        PERMISSIONS.VIEW_FINANCIALS,
        PERMISSIONS.MANAGE_PAYMENTS,
        PERMISSIONS.VIEW_COMMISSIONS,
        PERMISSIONS.EDIT_COMMISSIONS,
        PERMISSIONS.MANAGE_DAILY_CLOSE,
    ],
    'Bilhetes': [
        PERMISSIONS.VIEW_TICKETS,
        PERMISSIONS.CANCEL_TICKET,
        PERMISSIONS.VALIDATE_TICKET,
        PERMISSIONS.EDIT_TICKET,
    ],
    'Sistema': [
        PERMISSIONS.MANAGE_SETTINGS,
        PERMISSIONS.MANAGE_COMPANY,
        PERMISSIONS.MANAGE_DEVICES,
        PERMISSIONS.VIEW_LOGS,
        PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    ],
    'Palpita Ai': [
        PERMISSIONS.VIEW_PALPITA,
        PERMISSIONS.CREATE_PALPITA_DRAW,
        PERMISSIONS.MANAGE_PALPITA_RESULTS,
    ],
};
