-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "mainMatchMessage" TEXT DEFAULT 'ACERTANDO TODOS OS NÚMEROS NA ORDEM',
ADD COLUMN     "promptMessage" TEXT DEFAULT 'VOCÊ GANHA SE ACERTAR EM UMA DAS FEZINHAS';
